name       : python-pyte
version    : 0.8.0
release    : 5
source     :
    - https://github.com/selectel/pyte/archive/0.8.0.tar.gz : 80f77a4f8a325faf761c22eb8ad597671e25d0de524c68d42dc765c52bf5be70
license    : LGPL-3.0-only
component  : programming.python
summary    : Simple VTXXX-compatible linux terminal emulator
description: |
    It’s an in memory VTXXX-compatible terminal emulator. XXX stands for a series of video terminals, developed by DEC between 1970 and 1995. The first, and probably the most famous one, was VT100 terminal, which is now a de-facto standard for all virtual terminal emulators.
builddeps  :
    - pytest-runner
    - python-wcwidth
rundeps    :
    - python-wcwidth
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
