name       : python-pyte
version    : 0.7.0
release    : 2
source     :
    - https://github.com/selectel/pyte/archive/0.7.0.tar.gz : 3d0b6909a68fac1856f325c7d0d7434e13ee2ab91ca09fcc762ee03a64e5fdee
license    : LGPL-3.0
component  : programming.python
summary    : Simple VTXXX-compatible linux terminal emulator
description: |
    It’s an in memory VTXXX-compatible terminal emulator. XXX stands for a series of video terminals, developed by DEC between 1970 and 1995. The first, and probably the most famous one, was VT100 terminal, which is now a de-facto standard for all virtual terminal emulators.
builddeps  :
    - pytest-runner
    - python-setuptools
    - python-wcwidth
rundeps    :
    - python-wcwidth
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py pytest
    popd
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py pytest
    popd
