name       : python-pyte
version    : 0.8.1
release    : 8
source     :
    - https://github.com/selectel/pyte/archive/refs/tags/0.8.1.tar.gz : 5bd1703d007310cd502f213b3f1d45c6f94602330fc5b14e1e5afaab5060ffca
license    : LGPL-3.0-only
component  : programming.python
summary    : Simple VTXXX-compatible linux terminal emulator
description: |
    It’s an in memory VTXXX-compatible terminal emulator. XXX stands for a series of video terminals, developed by DEC between 1970 and 1995. The first, and probably the most famous one, was VT100 terminal, which is now a de-facto standard for all virtual terminal emulators.
builddeps  :
    - pytest-runner
    - python-wcwidth
rundeps    :
    - python-wcwidth
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
